### ISSUE TITLE
Multiple Sensors

### ISSUE THREAD

**Issue by Fannangir** [dubilyer/ramzor_sensor#7]
Hi,
Is there an option to monitor multiple cities?
Thanks.

**Comment by dubilyer** [comment]
I will try to implement.

**Comment by dubilyer** [comment]
Supported in 1.1.7. @Fannangir, please check and confirm.

**Comment by Fannangir** [comment]
Thank you very much @dubilyer.
Just tried to add 2 sensors, works as expected.
